### ISSUE TITLE
backend blogs no longer working

### ISSUE THREAD

**Issue by golles** [vova07/yii2-start-blogs-module#7]
If I open blogs in the backend, it tries to render the frontend blogs..

"Getting unknown property: vova07\blogs\models\backend\BlogSearch::created"
File: in .../vendor/vova07/yii2-start-blogs-module/views/frontend/default/_index_item.php – yii\db\BaseActiveRecord::__get('created') at line 30

**Comment by fr8ak2** [comment]
Check your backend config main.php file.
Change blog section _isBackend from false to true.
